In [1]:
#Problem Statement 1: 
#Write a function so that the columns of the output matrix are powers of the input vector. 
#The order of the powers is determined by the increasing boolean argument.
#Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise
#to the power  of N - i - 1. 
#HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.


In [13]:
#create a matrix with o/p column based on input vectors(N)
import numpy as np
x = np.array([1,2,3,4,5])
N=5
mtrx = np.column_stack([x**(N-i-1) for i in range(N)])
print('mtrx=',mtrx)

mtrx= [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [14]:
#create a matrix using np.vander function
x=np.array([1,2,3,4,5])
N=5
mtrx1 = np.vander(x,N,increasing=False)
print("mtrx1=",mtrx1)

mtrx1= [[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [15]:
#find the det of both matrix
np.linalg.det(mtrx)

287.9999999999977

In [16]:
np.linalg.det(mtrx1)

287.9999999999977